import '../model/atomic_step.dart';
import '../model/pin_task.dart';

/// Default sample pin titles mapped by ID for detecting untouched first-launch sample data.
const Map<String, String> defaultSampleTitles = {
  'sample-pin-1': 'Refactor drawer transition physics in UI',
  'sample-pin-2': 'Send project update email to team',
  'sample-pin-3': 'Draft architecture diagram for sync adapter',
  'sample-pin-4': 'Investigate offline IndexedDB fallback for Web',
  'sample-pin-5': 'Design app icon variations for smartphone home screen',
  'sample-pin-6': 'Setup automated GitHub Actions runner',
  'sample-pin-7': 'Initial Flutter companion app scaffold',
  'sample-pin-8': 'Define design tokens and calm color palette',
  'sample-pin-9': 'Unit test Base64 blueprint codec',
  'sample-pin-10': 'Implement atomic local storage adapter',
};

/// Generates initial companion sample pins on clean launch.
List<PinTask> generateSamplePins() {
  final now = DateTime.now();
  return [
    PinTask(
      id: 'sample-pin-1',
      title: 'Refactor drawer transition physics in UI',
      description:
          'Tune spring damping and stiffness for snappy tactile feel on mobile.',
      status: TaskStatus.today,
      isPinned: true,
      energyTag: 'medium-flow',
      estimatedMinutes: 30,
      tags: ['#dev', '#ui'],
      subtasks: [
        const AtomicStep(
          id: 's1-1',
          title: 'Audit current curve curves.easeInOut',
          isCompleted: true,
        ),
        const AtomicStep(
          id: 's1-2',
          title: 'Benchmark 60fps gesture response',
          isCompleted: false,
        ),
      ],
      createdAt: now.subtract(const Duration(hours: 2)),
      updatedAt: now,
    ),
    PinTask(
      id: 'sample-pin-2',
      title: 'Send project update email to team',
      description:
          'Brief 3-bullet summary of weekly achievements and blockers.',
      status: TaskStatus.today,
      isPinned: true,
      energyTag: 'low-friction',
      estimatedMinutes: 15,
      tags: ['#admin', '#quick-win'],
      createdAt: now.subtract(const Duration(hours: 1)),
      updatedAt: now,
    ),
    PinTask(
      id: 'sample-pin-3',
      title: 'Draft architecture diagram for sync adapter',
      description: 'Export SVG for documentation repository.',
      status: TaskStatus.today,
      isPinned: true,
      energyTag: 'deep-focus',
      estimatedMinutes: 45,
      tags: ['#arch', '#docs'],
      createdAt: now.subtract(const Duration(minutes: 40)),
      updatedAt: now,
    ),
    PinTask(
      id: 'sample-pin-4',
      title: 'Investigate offline IndexedDB fallback for Web',
      description: 'Verify storage quotas and cross-origin isolation.',
      status: TaskStatus.backlog,
      isPinned: false,
      energyTag: 'deep-focus',
      estimatedMinutes: 60,
      tags: ['#web', '#storage'],
      createdAt: now.subtract(const Duration(days: 1)),
      updatedAt: now,
    ),
    PinTask(
      id: 'sample-pin-5',
      title: 'Design app icon variations for smartphone home screen',
      description: 'Generate square and adaptive Android/iOS vectors.',
      status: TaskStatus.backlog,
      isPinned: false,
      energyTag: 'creative',
      estimatedMinutes: 30,
      tags: ['#design', '#mobile'],
      createdAt: now.subtract(const Duration(days: 2)),
      updatedAt: now,
    ),
    PinTask(
      id: 'sample-pin-6',
      title: 'Setup automated GitHub Actions runner',
      description: 'Ensure tests run on every pull request.',
      status: TaskStatus.backlog,
      isPinned: false,
      energyTag: 'medium-flow',
      estimatedMinutes: 30,
      tags: ['#ci', '#devops'],
      createdAt: now.subtract(const Duration(days: 3)),
      updatedAt: now,
    ),
    PinTask(
      id: 'sample-pin-7',
      title: 'Initial Flutter companion app scaffold',
      description: 'Setup base Riverpod container and FSD directory tree.',
      status: TaskStatus.done,
      isPinned: false,
      energyTag: 'low-friction',
      estimatedMinutes: 20,
      tags: ['#setup'],
      createdAt: now.subtract(const Duration(days: 4)),
      updatedAt: now,
      completedAt: now.subtract(const Duration(days: 3)),
    ),
    PinTask(
      id: 'sample-pin-8',
      title: 'Define design tokens and calm color palette',
      description: 'Curate dark slate and high contrast light mode tokens.',
      status: TaskStatus.done,
      isPinned: false,
      energyTag: 'creative',
      estimatedMinutes: 25,
      tags: ['#design'],
      createdAt: now.subtract(const Duration(days: 4)),
      updatedAt: now,
      completedAt: now.subtract(const Duration(days: 2)),
    ),
    PinTask(
      id: 'sample-pin-9',
      title: 'Unit test Base64 blueprint codec',
      description: 'Validate round-trip serialization and corruption guard.',
      status: TaskStatus.done,
      isPinned: false,
      energyTag: 'low-friction',
      estimatedMinutes: 15,
      tags: ['#test'],
      createdAt: now.subtract(const Duration(days: 3)),
      updatedAt: now,
      completedAt: now.subtract(const Duration(days: 1)),
    ),
    PinTask(
      id: 'sample-pin-10',
      title: 'Implement atomic local storage adapter',
      description: 'Verify temporary swap mechanism for zero corruptions.',
      status: TaskStatus.done,
      isPinned: false,
      energyTag: 'deep-focus',
      estimatedMinutes: 40,
      tags: ['#storage'],
      createdAt: now.subtract(const Duration(days: 2)),
      updatedAt: now,
      completedAt: now.subtract(const Duration(hours: 5)),
    ),
  ];
}
